name: Containerized Inner

on:
  workflow_call:
    inputs:
      jobname:
        required: true
        type: string
      image:
        required: true
        type: string
      os:
        required: false
        type: string

env:
  DEVELOPER: 1
  jobname: ${{inputs.jobname}}

jobs:
  containerized-build:
    name: Build
    runs-on: ubuntu-latest
    container: ${{inputs.image}}
    steps:
    - uses: actions/checkout@v1
    - name: Install Build Dependenciees
      run: ci/install-docker-dependencies.sh
    - name: Build Git & Generate Archive
      run: ci/make-test-artifacts.sh artifacts
    - name: zip up tracked files
      run: git archive -o artifacts/tracked.tar.gz HEAD
    - name: upload tracked files and build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{inputs.jobname}}-artifacts
        path: artifacts
  containerized-test:
    name: Test
    runs-on: ubuntu-latest
    needs: [containerized-build]
    container: ${{inputs.image}}
    steps:
    - name: download tracked files and build artifacts
      uses: actions/download-artifact@v1
      with:
        name: ${{inputs.jobname}}-artifacts
        path: ${{github.workspace}}
    - name: extract tracked files and build artifacts
      shell: bash
      run: tar xf artifacts.tar.gz && tar xf tracked.tar.gz
    - name: Install Build Dependenciees
      run: ci/install-dependencies.sh
    - name: Run Tests
      run: ci/run-test.sh
    - name: print test failures
      if: failure() && env.FAILED_TEST_ARTIFACTS != ''
      shell: bash
      run: ci/print-test-failures.sh
    - name: Upload failed tests' directories
      if: failure() && env.FAILED_TEST_ARTIFACTS != ''
      uses: actions/upload-artifact@v1
      with:
        name: failed-tests-${{inputs.jobname}}
        path: ${{env.FAILED_TEST_ARTIFACTS}}
  containerized-perf:
    name: Performance tests
    needs: [containerized-build]
    runs-on: ubuntu-latest
    container: ${{inputs.image}}
    steps:
    - name: download tracked files and build artifacts
      uses: actions/download-artifact@v1
      with:
        name: ${{inputs.jobname}}-artifacts
        path: ${{github.workspace}}
    - name: extract tracked files and build artifacts
      shell: bash
      run: tar xf artifacts.tar.gz && tar xf tracked.tar.gz
    - name: Install Build Dependenciees
      run: ci/install-dependencies.sh
    - name: Run Tests
      run: ci/run-perf.sh
