name: Regular Inner

on:
  workflow_call:
    inputs:
      jobname:
        required: true
        type: string
      cc:
        required: true
        type: string

      cc_package:
        required: false
        type: string

      pool: 
        required: true
        type: string

env:
  DEVELOPER: 1
  CC: ${{inputs.cc}}
  CC_PACKAGE: ${{inputs.cc_package}}
  jobname: ${{inputs.jobname}}
  runs_on_pool: ${{inputs.pool}}

jobs:
  regular-build:
    name: Build
    runs-on: ${{inputs.pool}}
    steps:
    - uses: actions/checkout@v2
    - name: Install Build Dependenciees
      run: ci/install-dependencies.sh
    - name: Build Git & Generate Archive
      run: ci/make-test-artifacts.sh artifacts
    - name: zip up tracked files
      run: git archive -o artifacts/tracked.tar.gz HEAD
    - name: upload tracked files and build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{inputs.jobname}}-artifacts
        path: artifacts 
  regular-test:
    name: Test
    needs: [regular-build]
    strategy:
      fail-fast: false
      matrix:
        nr: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    runs-on: ${{inputs.pool}}
    steps:
    - name: Install Build Dependenciees
      run: ci/install-dependencies.sh
    - name: download tracked files and build artifacts
      uses: actions/download-artifact@v2
      with:
        name: ${{inputs.jobname}}-artifacts
        path: ${{github.workspace}}
    - name: extract tracked files and build artifacts
      shell: bash
      run: tar xf artifacts.tar.gz && tar xf tracked.tar.gz
    - name: Run Tests
      run: ci/run-test-slice.sh ${{matrix.nr}} 10
    - name: print test failures
      if: failure() && env.FAILED_TEST_ARTIFACTS != ''
      shell: bash
      run: ci/print-test-failures.sh
    - name: Upload failed tests' directories
      if: failure() && env.FAILED_TEST_ARTIFACTS != ''
      uses: actions/upload-artifact@v2
      with:
        name: failed-tests-${{inputs.jobname}}
        path: ${{env.FAILED_TEST_ARTIFACTS}}
  regular-perf:
    name: Performance tests
    needs: [regular-build]
    runs-on: ${{inputs.pool}}
    steps:
    - name: Install Build Dependenciees
      run: ci/install-dependencies.sh
    - name: download tracked files and build artifacts
      uses: actions/download-artifact@v2
      with:
        name: ${{inputs.jobname}}-artifacts
        path: ${{github.workspace}}
    - name: extract tracked files and build artifacts
      shell: bash
      run: tar xf artifacts.tar.gz && tar xf tracked.tar.gz
    - name: Run Tests
      run: ci/run-perf.sh
